import json
from stemming.porter2 import stem
import sys

file = '{"status": "OK", "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html", "keywords": [{"relevance": "0.973138", "text": "marijuana dont attend", "sentiment": {"type": "positive"}}, {"relevance": "0.948609", "text": "dont attend parties", "sentiment": {"type": "neutral"}}, {"relevance": "0.846506", "text": "alcohol", "sentiment": {"type": "neutral"}}, {"relevance": "0.5262", "text": "loads", "sentiment": {"type": "neutral"}}, {"relevance": "0.503796", "text": "beer", "sentiment": {"type": "neutral"}}, {"relevance": "0.477682", "text": "winedont", "sentiment": {"type": "neutral"}}, {"relevance": "0.228192", "text": "wine", "sentiment": {"type": "neutral"}}], "totalTransactions": "2", "language": "english"}'

parsed_json = json.loads(file)
#print parsed_json['keywords'][1]['sentiment']['type']


list =[]

#relevant = (i for i in parsed_json['keywords'] if i[i]['relevance'] > 0.5)

i = 0
for each in parsed_json['keywords']:
    if float(each['relevance']) > 0.5 and str(each['sentiment']['type'])=='positive':
        list.append((stem(each['text']),float(each['relevance']),str(each['sentiment']['type'])))
print list

healthy_list=['training', 'gym', 'weight lifting', 'dumbells', 'protein', 'healthy diet','veggies','vegetable', 'salad','healthy food','workingout', 'running','treadmill', 'aerobics','elliptical','fitnessfreak','zumba', 'pushups', 'situps','yoga','fitness training' ]


drinking_list=['alcohol','booze','brew','cup','glass','liquor','refreshment','sip','draft','gulp'
,'libation','liquid','potable', 'potation','potion','shot','slug','spirits','after hours',
'bender','binge','drinking','booze','booze-up ','boozy','bottle','bottoms up','carouse'
,' down','drinking','drinking-up','hangover','piss-up','ply','snifter','rum','whiskey','vodka','wine','red wine', 'white wine']

cig_list=['ash','ashtray','baccy','bong','butt ','chain-smoke','cheroot','cig','cigar','cigarette','sxbutt','holder','lighter','paper','ciggie','drag',
'fag','filter','tip','hookah','lighter','mentholated','nicotine','snuff','snuffbox','tobacco','vaping', 'pipe tobacco', 'pipetobacco','ecigarettes','e-cigarettes','chewing tobacco','chewingtobacco','chain-smoker','chainsmoker','chain smoker']

drug_list=['Bath Salts','Cannabis','Cocaine','Devils Breath','Ecstasy','GHB','Hashish','Heroin','Ketamine','Kratom','Krokodil','LSD','Marijuana','MDMA','Mescaline','Opium','PCP ',
'Phencyclidine','Psilocybin','mushrooms','Rohypnol','Speed','methamphetamine','Synthetic Marijuana','TCP','Tenocyclidine']

occupation_list=['logging workers', 'Fishers', 'aircraft pilots', 'flight engineers', 'police', 'sheriff patrol officer', 'plumber', 'electrician', 'roofers',  'health care workers',
'icu nurse', 'registered nurse', 'nursing assistant', 'psychiatric aides', 'firefighters and prevention worker', 'firefighter', 'Laborers' ,'freight', 'stock and material movers',
'janitors', 'cleaners', 'heavy truck drivers', 'tractor drivers', 'trailer drivers', 'refuse material collector', 'recyclable material collectors',
'telecommunication line installers', 'miners', 'coal miner', 'crude oil engineer', 'petroleum engineer', 'nuclear scientist', 'radiologist']

s_healthy_list = []
s_drinking_list = []
s_cig_list = []
s_drug_list = []
s_occupation_list = []


for each in occupation_list:
    s_occupation_list.append(stem(each).lower())

for each in healthy_list:
    s_healthy_list.append(stem(each).lower())

for each in drinking_list:
    s_drinking_list.append(stem(each).lower())

for each in cig_list:
    s_cig_list.append(stem(each).lower())

for each in drug_list:
    s_drug_list.append(stem(each).lower())



min_ol = 0
ol = ''
min_hl = 0
hl = ''
min_dl = 0
dl = ''
min_cl = 0
cl = ''
min_drl = 0
drl = ''


for each in list:
    for ol in s_occupation_list:
        if str(each[0]) == ol:
            if each[1] > min_ol:
                min_ol = each[1]
                ol = each[0]
    for hl in s_healthy_list:
        if str(each[0]) == hl:
            if each[1] > min_hl:
                min_hl = each[1]
                hl = each[0]
    for dl in s_drinking_list:
        if str(each[0]) == dl:
            if each[1] > min_dl:
                min_dl = each[1]
                dl = each[0]
    for cl in s_cig_list:
        if str(each[0]) == cl:
            if each[1] > min_cl:
                min_cl = each[1]
                cl = each[0]
    for drl in s_drug_list:
        if str(each[0]) == drl:
            if each[1] > min_drl:
                min_drl = each[1]
                drl = each[0]



print min_dl
occu_primium = 5*min_ol
dri_primium = 4*min_dl
smok_primium = 10*min_cl
health_primium = -3*min_hl

print 'occupational risk='+ str(min_ol*100)+'%'+' premium='+str(occu_primium)
print 'drinking risk='+ str(min_dl*100)+'%'+' premium='+str(dri_primium)
print 'smoking risk='+ str(min_cl*100)+'%'+' premium='+str(smok_primium)
print 'drug_usage risk='+ str(min_drl*100)+'%'+' premium='+str(occu_primium)
print 'health benefit='+ str(min_hl*100)+'%'+' premium='+str(health_primium)


total_premium_add = smok_primium*0.6 + dri_primium*0.4 + occu_primium*0.48 + health_primium

print 'total premium add/deduct = '+str(total_premium_add)

#for deduction logic 210
# total_premium_add to be deleted from maximmum premium which is 10